ServerEvents.recipes(event => {

  console.log('[BLOODMAGIC.JS] - Rewriting History')
  // event.remove({ not: { type: 'bloodmagic:meteor' }, mod: 'bloodmagic' })
  event.remove({ type: 'bloodmagic:arc' , mod: 'bloodmagic' })
  event.remove({ type: 'bloodmagic:arc/furnace' , mod: 'bloodmagic' })
  // event.remove({ type: 'minecraft:smelting' , mod: 'bloodmagic' })
  event.remove({id : 'bloodmagic:blood_altar'})
  event.remove({id : 'bloodmagic:altar/slate'})
  event.remove({id : 'bloodmagic:array/spike'})
  event.remove({id : 'bloodmagic:array/night'})
  event.remove({id : 'bloodmagic:array/bounce'})
  event.remove({id : 'bloodmagic:array/updraft'})
  event.remove({id : 'bloodmagic:array/day'})
  event.remove({id : 'bloodmagic:array/movement'})
  event.remove({id : 'bloodmagic:alchemytable/gold_ore_from_gilded'})
  event.remove({id : 'bloodmagic:alchemytable/corrupted_coal'})
  event.remove({id : 'bloodmagic:alchemytable/sand_coal'})
  event.remove({id : 'bloodmagic:alchemytable/corrupted_gold'})
  event.remove({id : 'bloodmagic:alchemytable/corrupted_copper'})
  event.remove({id : 'bloodmagic:alchemytable/sand_iron'})
  event.remove({id : 'bloodmagic:alchemytable/gunpowder'})
  event.remove({id : 'bloodmagic:alchemytable/clay_from_sand'})
  event.remove({id : 'bloodmagic:alchemytable/string'})
  event.remove({id : 'bloodmagic:alchemytable/sulfur_from_sigil'})
  event.remove({id : 'bloodmagic:alchemytable/saltpeter'})
  event.remove({id : 'bloodmagic:alchemytable/saltpeter'})
  event.remove({id : 'bloodmagic:alchemytable/corrupted_iron'})
  event.remove({id : 'bloodmagic:alchemytable/sulfur_from_lava'})

  event.recipes.bloodmagic.altar('cosmiccore:trinavine_dust', 'gtceu:trinium_dust').drainRate(50).consumptionRate(25).altarSyphon(2500)
  event.recipes.bloodmagic.altar('bloodmagic:blankslate', 'gtceu:carbon_fiber_plate').drainRate(50).consumptionRate(25).altarSyphon(1000)

  event.recipes.gtceu.compressor('slate_to_rune')
    .itemInputs('9x bloodmagic:blankslate')
    .itemOutputs('bloodmagic:blankrune')
    .duration(240)
    .EUt(GTValues.VA[GTValues.IV]);
  event.shapeless('bloodmagic:sacrificialdagger', [
    'gtceu:tungsten_steel_knife'
  ])
})